// <auto-generated />
namespace BookRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changeddatatypeforadditionalChargefiled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeddatatypeforadditionalChargefiled));
        
        string IMigrationMetadata.Id
        {
            get { return "202006021950217_changed datatype for additionalCharge filed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
