// <auto-generated />
namespace BookRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class columnnamechangedfromPricetoPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnnamechangedfromPricetoPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202004111309506_column name changed from Price to Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
